### ISSUE TITLE
如何配置自动抓取下一页的数据

### ISSUE THREAD

**Issue by yummykang** [bruceq/Gather-Platform#1]
如何配置自动抓取下一页的数据，我需要抓取一个列表，是分页的，但是不知道怎么配置下一页

**Comment by bruceq** [comment]
需要再解析中找到页面对应的下一页地址，通过page.addtarget(s)的方法，把下一页的地址添加到队列中，之后进行下一页的解析

**Comment by yummykang** [comment]
thanks
